#!/usr/bin/env python3
"""Run the independent Nihonga Now crawler.

The command writes a compact local report by default. ``--write`` is the
explicit opt-in for Supabase and only writes the news tables; the Instagram
crawler and Artist write path are never imported or called.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
import tempfile
import math
import time
from contextlib import contextmanager
from datetime import date, datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Callable, Iterable, Mapping
from urllib.error import HTTPError, URLError
from urllib.parse import quote
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from news.ai_processor import AIProcessor, AIProcessorError, determine_status, process_news_with_ai
from news.config import load_sources
from news.crawler import (
    RawNewsItem,
    NewsCrawler,
    canonical_url,
    load_known_titles,
    load_known_urls,
    normalize_text,
    source_url_allowed,
)
from news.matching import match_artists


NEWS_FIELDS = (
    "title", "summary", "category", "source_name", "source_url", "source_item_id",
    "content_fingerprint", "published_at", "start_date", "end_date", "venue", "image_url",
    "raw_artist_names", "tags", "relevance_score", "status",
)
ALLOWED_CATEGORIES = {"exhibition", "open_call", "artist_news", "museum", "nihonga_news"}
TOKYO = timezone(timedelta(hours=9), name="JST")


@contextmanager
def _state_file_lock(path: Path, *, timeout: float = 30.0):
    """Serialize state-file reads/writes across overlapping crawler runs.

    The lock is a tiny O_EXCL marker rather than a platform-specific advisory
    lock, so it works for the Windows manual-run workflow as well as POSIX.
    It is held only while reading or merging state; network and AI work remain
    outside the critical section.
    """

    path.parent.mkdir(parents=True, exist_ok=True)
    lock_path = path.with_name(f".{path.name}.lock")
    deadline = time.monotonic() + max(0.1, float(timeout))
    handle = None
    while handle is None:
        try:
            handle = os.open(lock_path, os.O_CREAT | os.O_EXCL | os.O_WRONLY)
            try:
                os.write(handle, f"{os.getpid()}\n".encode("ascii", errors="ignore"))
            except Exception:
                os.close(handle)
                handle = None
                lock_path.unlink(missing_ok=True)
                raise
        except FileExistsError:
            if time.monotonic() >= deadline:
                raise TimeoutError(f"timed out waiting for news state lock: {path}")
            time.sleep(0.05)
    try:
        yield
    finally:
        try:
            os.close(handle)
        finally:
            try:
                lock_path.unlink()
            except FileNotFoundError:
                pass


def _state_entry_merge(current: Mapping[str, Any] | None, incoming: Mapping[str, Any]) -> dict[str, Any]:
    """Merge concurrent state updates without mixing markers and payloads.

    A later run can finish with an AI or database error after an overlapping
    run has already succeeded.  OR-ing completion flags onto the later,
    incomplete record would make the state look complete while dropping the
    successful summary.  Select a coherent record version first, then retain
    durable markers only when the marker was produced for that same version.
    """

    if not isinstance(current, Mapping):
        return dict(incoming)
    current_at = normalize_text(current.get("processed_at"))
    incoming_at = normalize_text(incoming.get("processed_at"))
    # Both timestamps are UTC ISO strings generated by this command.
    newest = incoming if incoming_at >= current_at else current
    other = current if newest is incoming else incoming
    newest_record = newest.get("record") if isinstance(newest.get("record"), Mapping) else {}
    other_record = other.get("record") if isinstance(other.get("record"), Mapping) else {}

    # AI output is valid for the same source snapshot even when its normalized
    # title/date fingerprint differs from the raw crawler record.  If the
    # newest overlapping run did not process AI, retain the older successful
    # payload only when the source URL and bounded excerpt still identify the
    # same snapshot.
    selected = newest
    selected_record = newest_record
    if newest.get("ai_processed") is not True and other.get("ai_processed") is True and _same_source_snapshot(newest_record, other_record):
        selected = other
        selected_record = other_record

    merged = dict(selected)
    # Keep the newest wall-clock marker so subsequent readers know when the
    # merge happened, while the rest of the payload remains coherent.
    merged["processed_at"] = max(current_at, incoming_at)
    for marker in ("ai_processed", "database_written", "links_written"):
        merged[marker] = any(
            entry.get(marker) is True
            and _same_persisted_record(selected_record, entry.get("record") if isinstance(entry.get("record"), Mapping) else {})
            for entry in (current, incoming)
        )
    return merged


def _same_source_snapshot(left: Mapping[str, Any], right: Mapping[str, Any]) -> bool:
    """Return whether two state records came from the same fetched source."""

    left_url = canonical_url(left.get("source_url"))
    right_url = canonical_url(right.get("source_url"))
    if not left_url or left_url != right_url:
        return False
    left_item = normalize_text(left.get("source_item_id"))
    right_item = normalize_text(right.get("source_item_id"))
    if left_item and right_item and left_item != right_item:
        return False
    left_excerpt = normalize_text(left.get("raw_excerpt"), 1400)
    right_excerpt = normalize_text(right.get("raw_excerpt"), 1400)
    if left_excerpt and right_excerpt:
        return left_excerpt == right_excerpt
    # Older state files may not have retained the bounded excerpt.  The URL
    # and source item id are the remaining stable identity in that case.
    return bool(left_item and right_item and left_item == right_item)


def _same_persisted_record(left: Mapping[str, Any], right: Mapping[str, Any]) -> bool:
    """Return whether completion markers apply to the same DB representation."""

    if not _same_source_snapshot(left, right):
        return False
    for key in ("title", "summary", "category", "source_name", "content_fingerprint", "published_at", "start_date", "end_date", "venue", "raw_artist_names", "tags", "status"):
        if left.get(key) != right.get(key):
            return False
    return True


def _write_json_atomic(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    handle = tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=path.parent, prefix=f".{path.name}.", suffix=".tmp", delete=False)
    temporary = Path(handle.name)
    try:
        with handle:
            json.dump(value, handle, ensure_ascii=False, indent=2)
            handle.write("\n")
            handle.flush()
        temporary.replace(path)
    finally:
        if temporary.exists():
            temporary.unlink()


def _logger(path: Path | None) -> Callable[..., None]:
    def log(event: str, **fields: Any) -> None:
        if not path:
            return
        path.parent.mkdir(parents=True, exist_ok=True)
        record = {"timestamp": datetime.now(timezone.utc).isoformat(), "event": event}
        record.update({key: str(value)[:300] for key, value in fields.items() if key not in {"body", "html", "excerpt", "summary"}})
        with path.open("a", encoding="utf-8") as stream:
            stream.write(json.dumps(record, ensure_ascii=False, separators=(",", ":")) + "\n")

    return log


def _category(item: Mapping[str, Any]) -> str:
    value = normalize_text(item.get("category")).lower()
    if value in ALLOWED_CATEGORIES:
        return value
    text = " ".join(normalize_text(item.get(key)) for key in ("title", "summary", "venue")).lower()
    if any(term in text for term in ("募集", "応募", "公募", "参加者")):
        return "open_call"
    if any(term in text for term in ("展覧", "展示", "個展", "巡回", "会期", "日本画展")):
        return "exhibition"
    if any(term in text for term in ("作家", "画家", "受賞", "入選")):
        return "artist_news"
    return "nihonga_news"


def _fingerprint(item: Mapping[str, Any]) -> str:
    title = normalize_text(item.get("title")).casefold()
    published_at = normalize_text(item.get("published_at"))
    start_date = normalize_text(item.get("start_date"))
    end_date = normalize_text(item.get("end_date"))
    venue = normalize_text(item.get("venue")).casefold()
    source = normalize_text(item.get("source_name")).casefold()
    # Keep source and venue in the event identity. Official institutions may
    # publish same-titled annual shows, or the same title for different venues;
    # those are separate records even when their dates happen to match.
    values = (
        title,
        published_at,
        start_date,
        end_date,
        venue,
        source,
    )
    return hashlib.sha256("|".join(values).encode("utf-8")).hexdigest()


def _iso_date_or_none(value: Any) -> str | None:
    text = normalize_text(value, 20)
    if not text:
        return None
    try:
        # ``fromisoformat`` alone accepts a few unwanted forms; database date
        # fields and AI output deliberately use one canonical format.
        if len(text) != 10 or text[4] != "-" or text[7] != "-":
            return None
        return date.fromisoformat(text).isoformat()
    except (TypeError, ValueError, OverflowError):
        return None


def _record(raw: RawNewsItem | Mapping[str, Any]) -> dict[str, Any] | None:
    is_raw_candidate = isinstance(raw, RawNewsItem)
    value = raw.as_dict() if is_raw_candidate else dict(raw)
    title = normalize_text(value.get("title"), 300)
    source_url = canonical_url(value.get("source_url"), value.get("source_url"))
    if not title or not source_url:
        return None
    names = value.get("raw_artist_names", value.get("artist_names", []))
    if isinstance(names, str):
        names = [names]
    names = list(dict.fromkeys(normalize_text(name, 120) for name in (names if isinstance(names, list) else []) if normalize_text(name, 120)))
    tags = value.get("tags", [])
    if isinstance(tags, str):
        tags = [tags]
    tags = list(dict.fromkeys(normalize_text(tag, 60).lstrip("#") for tag in (tags if isinstance(tags, list) else []) if normalize_text(tag, 60).lstrip("#")))
    status = normalize_text(value.get("status")).lower()
    if status not in {"candidate", "published", "rejected", "expired"}:
        status = "candidate"
    score = value.get("relevance_score")
    try:
        score = float(score) if score is not None and math.isfinite(float(score)) and 0 <= float(score) <= 1 else None
    except (TypeError, ValueError, OverflowError):
        score = None
    # Keep a durable marker when a source supplied a non-empty but malformed
    # date.  Converting it directly to ``None`` would make publication rules
    # treat a parse failure as an intentionally absent date.
    date_parse_error = value.get("date_parse_error") is True or any(
        bool(normalize_text(value.get(field))) and _iso_date_or_none(value.get(field)) is None
        for field in ("published_at", "start_date", "end_date")
    )
    record = {
        "title": title,
        # Crawler text is local processor input, never the public summary.
        # Only the AI processor can supply the original short summary stored in
        # Supabase and rendered by the frontend.
        "summary": "" if is_raw_candidate else normalize_text(value.get("summary"), 600),
        "raw_excerpt": normalize_text(
            value.get("raw_excerpt") or value.get("excerpt") or (value.get("summary") if value.get("status") == "candidate" else ""),
            1400,
        ),
        "category": _category(value),
        "source_name": normalize_text(value.get("source_name"), 160),
        "source_url": source_url,
        "source_item_id": normalize_text(value.get("source_item_id"), 120),
        "content_fingerprint": normalize_text(value.get("content_fingerprint"), 64).lower(),
        "published_at": _iso_date_or_none(value.get("published_at")),
        "start_date": _iso_date_or_none(value.get("start_date")),
        "end_date": _iso_date_or_none(value.get("end_date")),
        "venue": normalize_text(value.get("venue"), 160),
        "image_url": "",
        "raw_artist_names": names,
        "tags": tags,
        "relevance_score": score,
        # Raw crawler items default to candidate, while persisted state keeps
        # a previously determined status so a failed database retry cannot
        # downgrade a published record.
        "status": status,
        "source_key": normalize_text(value.get("source_key"), 120),
        "date_parse_error": date_parse_error,
    }
    return record


def _deduplicate(items: Iterable[dict[str, Any]], known_urls: Iterable[str] = (), known_fingerprints: Iterable[str] = ()) -> tuple[list[dict[str, Any]], int]:
    urls = {canonical_url(value) for value in known_urls if canonical_url(value)}
    fingerprints = set(known_fingerprints)
    unique: list[dict[str, Any]] = []
    duplicates = 0
    for item in items:
        url = item["source_url"]
        fingerprint = normalize_text(item.get("content_fingerprint"), 64).lower() or _fingerprint(item)
        if url in urls or fingerprint in fingerprints:
            duplicates += 1
            continue
        urls.add(url)
        fingerprints.add(fingerprint)
        if not item["source_item_id"]:
            item["source_item_id"] = hashlib.sha256(f"{url}\n{item['title']}".encode("utf-8")).hexdigest()[:24]
        item["content_fingerprint"] = fingerprint
        item["_fingerprint"] = fingerprint
        unique.append(item)
    return unique, duplicates


def _public_item(item: Mapping[str, Any]) -> dict[str, Any]:
    return {key: item.get(key) for key in NEWS_FIELDS}


def _report_item(item: Mapping[str, Any]) -> dict[str, Any]:
    """Include bounded local processor input without adding it to DB fields."""

    return _public_item(item) | {
        "raw_excerpt": normalize_text(item.get("raw_excerpt"), 1400),
        "artist_ids": list(item.get("artist_ids", [])),
        "ai_error": normalize_text(item.get("ai_error"), 300),
    }


def _expire(item: dict[str, Any], today: date) -> None:
    if item.get("status") != "published" or item.get("category") not in {"exhibition", "open_call"} or not item.get("end_date"):
        return
    try:
        if date.fromisoformat(str(item["end_date"])) < today:
            item["status"] = "expired"
    except ValueError:
        return


def _load_json(path: Path, fallback: Any) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError, TypeError, json.JSONDecodeError):
        return fallback


class SupabaseNewsStore:
    """Small REST adapter scoped to ``news`` and ``news_artists`` only."""

    def __init__(self, timeout: float = 20) -> None:
        self.url = os.getenv("SUPABASE_URL", "").rstrip("/")
        self.key = os.getenv("SUPABASE_SERVICE_ROLE_KEY", "")
        self.timeout = timeout
        if not self.url or not self.key:
            raise RuntimeError("SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required for --write")

    def request(self, path: str, method: str = "GET", payload: Any = None, headers: Mapping[str, str] | None = None) -> Any:
        request = Request(
            f"{self.url}/rest/v1/{path}",
            data=json.dumps(payload, ensure_ascii=False).encode("utf-8") if payload is not None else None,
            headers={"apikey": self.key, "Authorization": f"Bearer {self.key}", "Content-Type": "application/json", **(headers or {})},
            method=method,
        )
        try:
            with urlopen(request, timeout=self.timeout) as response:
                body = response.read()
        except HTTPError as error:
            failure = RuntimeError(f"Supabase request failed: HTTP {error.code}")
            setattr(failure, "status", error.code)
            raise failure from error
        except (URLError, TimeoutError, OSError) as error:
            raise RuntimeError(f"Supabase request failed: {type(error).__name__}") from error
        if not body:
            return None
        try:
            return json.loads(body.decode("utf-8", errors="replace"))
        except json.JSONDecodeError as error:
            raise RuntimeError("Supabase returned invalid JSON") from error

    def _paged(self, path: str, page_size: int = 1000) -> list[dict[str, Any]]:
        rows: list[dict[str, Any]] = []
        for offset in range(0, 100000, page_size):
            separator = "&" if "?" in path else "?"
            page = self.request(f"{path}{separator}limit={page_size}&offset={offset}") or []
            if not isinstance(page, list):
                break
            rows.extend(row for row in page if isinstance(row, Mapping))
            if len(page) < page_size:
                break
        return rows

    def existing(self) -> tuple[set[str], set[str]]:
        rows = self._paged("news?select=source_url,title,content_fingerprint,published_at,start_date,end_date&order=id")
        return (
            {canonical_url(row.get("source_url")) for row in rows if canonical_url(row.get("source_url"))},
            {
                normalize_text(row.get("content_fingerprint"), 64).lower() or _fingerprint(row)
                for row in rows
                if isinstance(row, Mapping)
            },
        )

    def artists(self) -> list[dict[str, Any]]:
        return self._paged("artists?select=*&order=id")

    def upsert(self, item: Mapping[str, Any]) -> dict[str, Any]:
        try:
            value = self.request(
                "news?on_conflict=source_url",
                "POST",
                _public_item(item),
                {"Prefer": "resolution=ignore-duplicates,return=representation"},
            )
        except RuntimeError as error:
            if getattr(error, "status", None) != 409:
                raise
            value = []
        inserted = value[0] if isinstance(value, list) and value else (value if isinstance(value, dict) else {})
        if inserted:
            return {**inserted, "_write_applied": True}

        # Resolve the URL identity first. A content fingerprint can be shared
        # by syndicated official pages; it must never cause us to overwrite
        # the canonical source URL of an existing record.
        existing: dict[str, Any] = {}
        source_url = canonical_url(item.get("source_url"))
        if source_url:
            rows = self.request(f"news?source_url=eq.{quote(source_url, safe='')}&select=*&limit=1") or []
            if isinstance(rows, list) and rows:
                existing = rows[0]
        fingerprint = normalize_text(item.get("content_fingerprint"), 64).lower()
        if fingerprint:
            rows = self.request(f"news?content_fingerprint=eq.{quote(fingerprint, safe='')}&select=*&limit=1") or []
            fingerprint_row = rows[0] if isinstance(rows, list) and rows else None
            if isinstance(fingerprint_row, Mapping):
                fingerprint_url = canonical_url(fingerprint_row.get("source_url"))
                # A fingerprint conflict must never patch a different
                # canonical URL. This check is required even when the URL
                # lookup above found an existing row, because PATCH would
                # otherwise surface a 409 and leave links perpetually pending.
                if fingerprint_url and fingerprint_url != source_url:
                    return {**fingerprint_row, "_write_applied": False, "_duplicate": True}
                if not existing:
                    existing = dict(fingerprint_row)
        if not existing or not existing.get("id"):
            return {}

        incoming_status = normalize_text(item.get("status")).lower()
        existing_status = normalize_text(existing.get("status")).lower() or "candidate"
        upgradable = {
            # A candidate may be retried after detail/AI enrichment even when
            # it remains incomplete; never downgrade a published record.
            "candidate": {"candidate"},
            "rejected": {"candidate"},
            "published": {"candidate", "rejected", "published", "expired"},
            "expired": {"candidate", "rejected", "published", "expired"},
        }
        if existing_status not in upgradable.get(incoming_status, set()):
            return {**existing, "_write_applied": False}
        rows = self.request(
            f"news?id=eq.{quote(str(existing['id']), safe='')}&status=eq.{quote(existing_status, safe='')}&select=*",
            "PATCH",
            _public_item(item),
            {"Prefer": "return=representation"},
        ) or []
        updated = rows[0] if isinstance(rows, list) and rows else existing
        return {**updated, "_write_applied": bool(isinstance(rows, list) and rows)}

    def sync_links(self, news_id: str, artist_ids: Iterable[str]) -> None:
        desired = {str(artist_id) for artist_id in artist_ids if artist_id}
        existing_rows = self.request(
            f"news_artists?news_id=eq.{quote(news_id, safe='')}&select=artist_id&limit=1000"
        ) or []
        existing = {
            str(row.get("artist_id"))
            for row in existing_rows
            if isinstance(row, Mapping) and row.get("artist_id")
        }
        to_add = desired - existing
        if to_add:
            rows = [{"news_id": news_id, "artist_id": artist_id} for artist_id in sorted(to_add)]
            # Add first. If insertion fails, stale links remain intact and a
            # later retry can reconcile them without data loss.
            self.request("news_artists", "POST", rows, {"Prefer": "resolution=ignore-duplicates,return=minimal"})
        stale = existing - desired
        if stale:
            encoded = ",".join(quote(value, safe="") for value in sorted(stale))
            self.request(
                f"news_artists?news_id=eq.{quote(news_id, safe='')}&artist_id=in.({encoded})",
                "DELETE",
            )

    def expire_published(self, today: date) -> int:
        rows = self.request(
            "news?status=eq.published&category=in.(exhibition,open_call)"
            f"&end_date=lt.{today.isoformat()}&select=id",
            "PATCH",
            {"status": "expired"},
            {"Prefer": "return=representation"},
        )
        return len(rows) if isinstance(rows, list) else 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Fetch trusted Nihonga Now source candidates")
    parser.add_argument("--config", help="source JSON file (defaults to news/sources.json)")
    parser.add_argument("--known-file", help="prior report/state JSON; source_url values are skipped")
    parser.add_argument("--state-file", default="imports/news-crawler-state.json", help="local idempotency state file")
    parser.add_argument("--out", default="imports/news-candidates.json", help="atomic JSON output path")
    parser.add_argument("--log-file", help="optional JSONL event log")
    parser.add_argument("--timeout", type=float, default=20, help="per-request timeout in seconds")
    parser.add_argument("--retry-attempts", type=int, default=2)
    parser.add_argument("--retry-backoff", type=float, default=0.5)
    parser.add_argument("--process-ai", action="store_true", help="enrich candidates through OPENAI_* configuration")
    parser.add_argument("--write", action="store_true", help="upsert news records into Supabase")
    parser.add_argument("--refresh", action="store_true", help="reprocess URLs recorded in local state")
    return parser


def run(args: argparse.Namespace) -> dict[str, Any]:
    sources = load_sources(args.config)
    state_path = Path(args.state_file)
    # Read under the same lock used by the final merge. The network/AI work
    # deliberately happens after releasing it so overlapping manual runs do
    # not serialize on slow source endpoints.
    with _state_file_lock(state_path):
        state = _load_json(state_path, {})
    processed = state.get("processed", {}) if isinstance(state, dict) and isinstance(state.get("processed"), dict) else {}
    known_path = Path(args.known_file) if args.known_file else state_path
    known_urls = set() if args.refresh else load_known_urls(known_path)
    known_titles = set() if args.refresh else load_known_titles(known_path)
    logger = _logger(Path(args.log_file) if args.log_file else None)
    crawler = NewsCrawler(sources, timeout=args.timeout, retry_attempts=args.retry_attempts, retry_backoff=args.retry_backoff, logger=logger)
    # URL is the durable cross-run identity. The crawler only uses a
    # title-only fallback for undated, venue-less duplicates in one listing;
    # dated/venue-bearing same-title events remain eligible for this batch.
    fetched = crawler.crawl(known_urls, known_titles)
    raw_items = [_record(item) for item in fetched.get("items", [])]
    new_records = [item for item in raw_items if item]
    pending_records: list[dict[str, Any]] = []
    if (args.process_ai or args.write) and not args.refresh:
        for entry in processed.values():
            if not isinstance(entry, Mapping) or not isinstance(entry.get("record"), Mapping):
                continue
            needs_ai = args.process_ai and entry.get("ai_processed") is not True
            needs_write = args.write and (
                entry.get("database_written") is not True
                or entry.get("links_written") is not True
            )
            if not needs_ai and not needs_write:
                continue
            pending_value = dict(entry["record"])
            # State v1 stored the bounded crawler excerpt in summary. Migrate
            # it to the local-only field when resuming without publishing it.
            pending_value["raw_excerpt"] = pending_value.get("raw_excerpt") or (
                pending_value.get("summary") if entry.get("ai_processed") is not True else ""
            ) or ""
            if entry.get("ai_processed") is not True:
                pending_value["summary"] = ""
            pending = _record(pending_value)
            if pending:
                pending["source_key"] = normalize_text(entry["record"].get("source_key"), 120)
                pending["_from_pending"] = True
                pending["_ai_processed"] = entry.get("ai_processed") is True
                pending_records.append(pending)

    store: SupabaseNewsStore | None = None
    database_errors: list[dict[str, Any]] = []
    existing_urls: set[str] = set()
    existing_fingerprints: set[str] = set()
    artists: list[dict[str, Any]] = []
    today = datetime.now(TOKYO).date()
    expired_existing = 0
    if args.write:
        try:
            store = SupabaseNewsStore(args.timeout)
        except Exception as error:
            database_errors.append(
                {"stage": "database-setup", "error": type(error).__name__, "message": str(error)[:300]}
            )
            store = None
        if store:
            # These reads improve deduplication and artist links, but a
            # temporary failure in either must not turn a recoverable write
            # batch into a no-op.  Database constraints still protect URL and
            # fingerprint identity while the next run retries the lookup.
            try:
                existing_urls, existing_fingerprints = store.existing()
            except Exception as error:
                database_errors.append(
                    {"stage": "database-existing", "error": type(error).__name__, "message": str(error)[:300]}
                )
            try:
                artists = store.artists()
            except Exception as error:
                database_errors.append(
                    {"stage": "database-artists", "error": type(error).__name__, "message": str(error)[:300]}
                )
            try:
                expired_existing = store.expire_published(today)
            except Exception as error:
                database_errors.append(
                    {"stage": "database-expiry", "error": type(error).__name__, "message": str(error)[:300]}
                )
    if not args.refresh:
        new_records, duplicate_records = _deduplicate(new_records, existing_urls, existing_fingerprints)
    else:
        new_records, duplicate_records = _deduplicate(new_records)
    pending_records, pending_duplicates = _deduplicate(pending_records)
    records, cross_duplicates = _deduplicate(pending_records + new_records)
    duplicate_records += pending_duplicates + cross_duplicates
    source_by_key = {source.key: source for source in sources}
    ai_processor = AIProcessor(
        timeout=args.timeout,
        retry_attempts=args.retry_attempts,
        retry_backoff=args.retry_backoff,
    ) if args.process_ai else None
    ai_stats = {
        "enabled": bool(ai_processor and ai_processor.enabled),
        "processed": 0,
        "paused": 0,
        "errors": 0,
        "halted": False,
    }
    output: list[dict[str, Any]] = []
    final_urls: set[str] = set()
    final_fingerprints: set[str] = set()
    matched_count = 0
    ai_halted = False
    for item in records:
        item.setdefault("_ai_processed", False)
        if ai_processor and not item["_ai_processed"] and not ai_halted:
            source = source_by_key.get(item.get("source_key"))
            trusted_source = bool(
                source
                and source.trusted_for_auto_publish
                and source_url_allowed(item.get("source_url", ""), source)
            )
            try:
                enriched = process_news_with_ai(item, processor=ai_processor)
                if enriched is None:
                    ai_stats["paused"] += 1
                else:
                    ai_stats["processed"] += 1
                    item["_ai_processed"] = True
                    for key in ("title", "summary", "category", "raw_artist_names", "venue", "start_date", "end_date", "tags", "relevance_score"):
                        source_key = "artist_names" if key == "raw_artist_names" else key
                        if source_key in enriched and enriched[source_key] not in (None, "", []):
                            item[key] = enriched[source_key]
                    item["status"] = determine_status(enriched, item, trusted_source=trusted_source, now=today)
            except Exception as error:
                ai_stats["errors"] += 1
                item["ai_error"] = str(error)[:300]
                # GitHub-hosted runners can occasionally be unable to reach
                # the configured provider. Keep first-party announcements
                # visible with their bounded source excerpt; untrusted items
                # remain candidates until AI review succeeds.
                if trusted_source and item.get("raw_excerpt"):
                    item["summary"] = normalize_text(item.get("raw_excerpt"), 600)
                    item["relevance_score"] = 0.9
                    item["status"] = "published"
                message = str(error).casefold()
                if any(term in message for term in ("http error 401", "http error 403", "http error 429", "quota", "rate limit")):
                    ai_halted = True
                    ai_stats["halted"] = True
        elif ai_processor and not item["_ai_processed"]:
            ai_stats["paused"] += 1
        # AI can normalize titles/dates. Recompute the durable fingerprint
        # after processing so database-level deduplication sees final facts.
        item["content_fingerprint"] = _fingerprint(item)
        _expire(item, today)
        # AI may normalize two distinct source titles into the same final
        # title/date identity.  Deduplicate that result before matching,
        # reporting, or writing so the batch remains idempotent in memory too.
        final_fingerprint = item["content_fingerprint"]
        if (
            item["source_url"] in final_urls
            or final_fingerprint in final_fingerprints
            or (final_fingerprint in existing_fingerprints and not item.get("_from_pending") and not args.refresh)
        ):
            duplicate_records += 1
            continue
        final_urls.add(item["source_url"])
        final_fingerprints.add(final_fingerprint)
        matching = match_artists(item.get("raw_artist_names", []), artists)
        item["artist_ids"] = [row["id"] for row in matching["matched"]]
        matched_count += len(item["artist_ids"])
        output.append(_report_item(item))

    stats = {
        "scanned": int(fetched.get("scanned", len(fetched.get("items", []))) or 0),
        "new": sum(not item.get("_from_pending") for item in records),
        "resumed_candidates": sum(bool(item.get("_from_pending")) for item in records),
        "duplicates": int(fetched.get("duplicates", 0) or 0) + duplicate_records,
        "updated": 0,
        "failed": len(fetched.get("errors", [])) + len(database_errors),
        "matched_artists": matched_count,
        "published": sum(item.get("status") == "published" for item in output),
        "candidate": sum(item.get("status") == "candidate" for item in output),
        "rejected": sum(item.get("status") == "rejected" for item in output),
        "expired": sum(item.get("status") == "expired" for item in output),
        "expired_existing": expired_existing,
    }
    database_written: dict[str, bool] = {}
    links_written: dict[str, bool] = {}
    # An attempted write must clear stale success markers until this run
    # confirms both the news row and its artist links. Otherwise a transient
    # failure on a previously successful record would be treated as complete
    # forever and never enter the pending retry set.
    if args.write:
        for item in output:
            database_written[item["source_url"]] = False
            links_written[item["source_url"]] = False
    if store:
        for item in output:
            try:
                saved = store.upsert(item)
                if not saved.get("id"):
                    raise RuntimeError("database did not return a news id")
                if saved.get("_duplicate"):
                    # A concurrent batch may have inserted the same final
                    # fingerprint under another URL. Keep the existing row
                    # untouched, including its artist links.
                    stats["duplicates"] += 1
                    database_written[item["source_url"]] = True
                    links_written[item["source_url"]] = True
                    continue
                database_written[item["source_url"]] = True
                # A non-applied upsert means the database already contains a
                # higher-priority state (for example published vs candidate).
                # Preserve its existing artist links instead of reconciling
                # them with the lower-priority incoming record.
                if saved.get("_write_applied") is not False:
                    store.sync_links(str(saved["id"]), item.get("artist_ids", []))
                links_written[item["source_url"]] = True
                stats["updated"] += 1
            except Exception as error:
                database_errors.append({"source": item.get("source_name"), "url": item.get("source_url"), "stage": "database", "error": type(error).__name__})
                stats["failed"] += 1

    generated_at = datetime.now(timezone.utc).isoformat()
    errors = list(fetched.get("errors", [])) + database_errors
    for item in records:
        state_record = _public_item(item)
        state_record["source_key"] = item.get("source_key", "")
        state_record["raw_excerpt"] = normalize_text(item.get("raw_excerpt"), 1400)
        # Keep parse diagnostics in the local retry state only; this is not a
        # public/database field and ensures a malformed source date remains a
        # candidate on a later --process-ai/--write resume.
        state_record["date_parse_error"] = bool(item.get("date_parse_error"))
        previous = processed.get(item["source_url"], {})
        previous_database_written = bool(isinstance(previous, Mapping) and previous.get("database_written") is True)
        previous_links_written = bool(isinstance(previous, Mapping) and previous.get("links_written") is True)
        processed[item["source_url"]] = {
            "status": item.get("status"),
            "processed_at": generated_at,
            "ai_processed": bool(item.get("_ai_processed")),
            # Do not mark a record as written merely because this invocation
            # did not request --write. This preserves a later write/AI retry.
            "database_written": database_written.get(item["source_url"], previous_database_written),
            "links_written": links_written.get(item["source_url"], previous_links_written),
            "record": state_record,
        }
    # Re-read and merge while holding the lock. A concurrent run may have
    # completed AI/database work after our initial read; preserve its durable
    # success markers and newest record payload instead of overwriting it.
    with _state_file_lock(state_path):
        latest_state = _load_json(state_path, {})
        latest_processed = (
            latest_state.get("processed", {})
            if isinstance(latest_state, Mapping) and isinstance(latest_state.get("processed"), Mapping)
            else {}
        )
        merged_processed = dict(latest_processed)
        for source_url, incoming in processed.items():
            previous = merged_processed.get(source_url)
            merged_processed[source_url] = _state_entry_merge(previous, incoming)
        _write_json_atomic(
            state_path,
            {
                "version": 3,
                "updated_at": generated_at,
                "processed": merged_processed,
                "seen_urls": sorted(merged_processed),
                "titles": sorted(
                    {
                        normalize_text(entry.get("record", {}).get("title"))
                        for entry in merged_processed.values()
                        if isinstance(entry, Mapping) and isinstance(entry.get("record"), Mapping) and normalize_text(entry["record"].get("title"))
                    }
                ),
            },
        )
        processed = merged_processed
    report = {"version": 1, "fetched_at": generated_at, "stats": stats, "items": output, "errors": errors, "sources": fetched.get("sources", []), "ai": ai_stats, "seen_urls": sorted(processed)}
    _write_json_atomic(Path(args.out), report)
    logger("batch-summary", **stats)
    return report


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    report = run(args)
    print(json.dumps({"ok": True, "stats": report["stats"], "errors": len(report["errors"]), "out": str(Path(args.out))}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
