const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");
const prefs = require("../public/index-preferences.js");
const vocabulary = require("../public/artist-vocabulary.js");
const index = require("../public/artist-index.js");
const data = new Map();
const storage = { getItem: (key) => data.get(key) || null, setItem: (key, value) => data.set(key, value) };
const denied = { getItem() { throw new Error("denied"); }, setItem() { throw new Error("denied"); } };
const users = [{ id: "user-a", status: "active" }, { id: "user-b", status: "active" }];
const artists = [{ id: "real-a", school: "東京藝術大学", region: "東京", styles: ["動物"] }, { id: "real-b" }];
for (const user of [null, {}, { guest: true }, { id: "user-a", guest: true }, { id: "user-a", status: "disabled" }]) {
  assert.equal(prefs.memberId(user), null);
  assert.equal(prefs.toggleFavorite(storage, user, "real-a", artists).ok, false);
  assert.deepEqual(prefs.favorites(storage, user), []);
}
assert.equal(data.size, 0, "Guests never write a favorite list");
assert.deepEqual(prefs.toggleFavorite(storage, users[0], "real-a", artists), { ok: true, saved: true });
assert.deepEqual(prefs.favorites(storage, users[0]), ["real-a"]);
assert.deepEqual(prefs.favorites(storage, users[1]), [], "Account B cannot see account A favorites");
assert.equal(prefs.toggleFavorite(storage, users[0], "invented", artists).ok, false);
assert.deepEqual(prefs.toggleFavorite(storage, users[0], "real-a", artists), { ok: true, saved: false });
assert.deepEqual(prefs.favorites(storage, users[0]), []);
assert.equal(prefs.toggleFavorite(denied, users[0], "real-a", artists).reason, "storage");
assert.deepEqual(prefs.favorites(denied, users[0]), []);
assert.deepEqual(prefs.favorites(null, users[0]), []);
data.set("nihonga:favorites:v1:user-a", "broken json");
assert.deepEqual(prefs.favorites(storage, users[0]), []);
data.set("nihonga:favorites:v1:user-a", JSON.stringify(["real-a", "real-a", null, 1, {}]));
assert.deepEqual(prefs.favorites(storage, users[0]), ["real-a"]);

const browse = { query: "东京艺大 & 花鳥", region: "東京", school: "東京藝術大学", tag: "動物", view: "list", limit: 72, scrollY: 2400, randomId: "real-a", password: "must-not-store", email: "must-not-store" };
const clean = prefs.sanitize(browse);
assert.equal(clean.limit, 72);
assert.equal(clean.scrollY, 2400);
assert.equal(clean.password, undefined);
assert.equal(clean.email, undefined);
assert.equal(prefs.write(storage, prefs.BROWSE_KEY, clean), true);
assert.deepEqual(prefs.sanitize(prefs.read(storage, prefs.BROWSE_KEY, {})), clean);
assert.equal(prefs.write(denied, prefs.BROWSE_KEY, clean), false);
assert.equal(prefs.sanitize({ limit: -10, scrollY: -1 }).limit, 12);
assert.equal(prefs.sanitize({ limit: Infinity }).limit, 12000);
assert.equal(prefs.fromUrl("https://example.org/").explicit, false);
const shared = prefs.shareUrl("https://example.org/?token=secret#home", browse, "ja");
const restored = prefs.fromUrl(shared);
assert.equal(restored.explicit, true);
assert.equal(restored.lang, "ja");
for (const key of ["query", "region", "school", "tag", "view"]) assert.equal(restored.browse[key], browse[key]);
for (const secret of ["secret", "token", "password", "email", "scrollY", "limit", "favorites", "user-a"]) assert.ok(!shared.includes(secret), `Shared link excludes ${secret}`);
const detail = prefs.fromUrl(prefs.shareUrl("https://example.org/", browse, "zh", "real-a"));
assert.equal(detail.artistId, "real-a");
assert.equal(detail.browse.query, "", "Artist sharing does not leak search filters");
for (const query of ["东京艺大", "Tokyo University of the Arts", "Geidai", "动物", "Animals", "東京藝術大学"]) assert.equal(index.matches(artists[0], { query }), true);
assert.equal(index.matches(artists[0], { region: "京都" }), false, "Aliases do not change exact filter matching");
assert.equal(vocabulary.label("東京藝術大学", "zh"), "东京艺术大学");
assert.equal(vocabulary.label("東京藝術大学", "ja"), "東京藝術大学");
assert.equal(vocabulary.label("unmapped", "en"), "unmapped");
assert.doesNotThrow(() => index.matches({ styles: "malformed", tags: {}, region: "__proto__" }));
assert.equal(artists[0].school, "東京藝術大学", "Translation never changes source values");

const context = vm.createContext({ localStorage: storage });
for (const file of ["i18n.js", "index-i18n.js", "index-experience-i18n.js"]) vm.runInContext(fs.readFileSync(path.join(__dirname, "../public", file), "utf8"), context);
assert.equal(vm.runInContext("I18N.current", context), "ja", "Japanese is the default language");
for (const preferredLanguage of ["zh", "en"]) {
  const preferredContext = vm.createContext({ localStorage: { getItem: () => preferredLanguage, setItem() {} } });
  vm.runInContext(fs.readFileSync(path.join(__dirname, "../public/i18n.js"), "utf8"), preferredContext);
  assert.equal(vm.runInContext("I18N.current", preferredContext), preferredLanguage, "Saved language preference is preserved");
}
const invalidLanguageContext = vm.createContext({ localStorage: { getItem: () => "invalid", setItem() {} } });
vm.runInContext(fs.readFileSync(path.join(__dirname, "../public/i18n.js"), "utf8"), invalidLanguageContext);
assert.equal(vm.runInContext("I18N.current", invalidLanguageContext), "ja", "Invalid language preference falls back to Japanese");
assert.doesNotThrow(() => vm.runInContext('I18N.setLang("invalid")', invalidLanguageContext));
assert.equal(vm.runInContext("I18N.current", invalidLanguageContext), "ja", "Invalid language selections fall back to Japanese");
const blockedLanguageContext = vm.createContext({ localStorage: denied });
vm.runInContext(fs.readFileSync(path.join(__dirname, "../public/i18n.js"), "utf8"), blockedLanguageContext);
assert.doesNotThrow(() => vm.runInContext('I18N.setLang("zh")', blockedLanguageContext));
assert.equal(vm.runInContext("I18N.current", blockedLanguageContext), "zh", "Language selection works without storage");
const translations = vm.runInContext("I18N.data", context);
assert.equal(translations.ja.recentUnavailable, "新たに加わった作家を、順次こちらで紹介します。", "Japanese Recently Added empty state uses the requested copy");
const html = fs.readFileSync(path.join(__dirname, "../public/index.html"), "utf8");
const app = fs.readFileSync(path.join(__dirname, "../public/app.js"), "utf8");
assert.match(html, /<section id="recent" class="index-section"[^>]*>/, "Recently Added section remains in the homepage markup");
assert.doesNotMatch(html.match(/<section id="recent"[\s\S]*?<\/section>/)?.[0] || "", /\shidden(?:=|\s|>)/, "Recently Added section is not statically hidden");
assert.match(app, /function enterWelcome\(\{ animate = true \} = \{\}\)/, "Welcome screen has an explicit resume path");
assert.match(app, /if \(restored\) enterWelcome\(\{ animate: false \}\)/, "Returning sessions skip the welcome screen");
const loginHtml = html.slice(html.indexOf('<div id="loginOverlay"'), html.indexOf('<div class="app-shell'));
assert.match(loginHtml, /id="loginTitle"[^>]*>メールでログイン</);
assert.match(loginHtml, /id="guestLoginButton"[^>]*>ゲストとして閲覧</);
assert.match(loginHtml, /id="loginLangSelect"[^>]*>.*?<option value="ja">日本語</s);
assert.match(loginHtml, /id="passwordInput"[^>]*placeholder="8文字以上"/);
assert.match(loginHtml, /パスワードを忘れた場合は、管理者にご連絡ください。/);
const keys = [...html.matchAll(/data-i18n(?:-placeholder|-aria-label)?="([^"]+)"/g)].map((match) => match[1]);
for (const lang of ["zh", "en", "ja"]) for (const key of keys) assert.ok(translations[lang][key], `${lang} is missing ${key}`);
for (const lang of ["zh", "en", "ja"]) assert.match(translations[lang].memberOnlyContribution, /登录|sign.?in|ログイン/i);
assert.match(fs.readFileSync(path.join(__dirname, "../public/index.html"), "utf8"), /data-member-only-form/);
for (const key of Object.keys(translations.en).filter((key) => key.startsWith("feature") || key.startsWith("account"))) {
  for (const lang of ["zh", "ja"]) assert.ok(translations[lang][key], `${lang} is missing account copy ${key}`);
}
const ids = [...html.matchAll(/\bid="([^"]+)"/g)].map((match) => match[1]);
assert.equal(ids.length, new Set(ids).size, "Unique HTML IDs");
for (const [, file] of html.matchAll(/(?:src|href)="([^"?#]+\.(?:js|css))(?:\?[^"#]*)?"/g)) assert.ok(fs.existsSync(path.join(__dirname, "../public", file)), `Missing asset ${file}`);
console.log("Experience tests passed: guest/member separation, per-account favorites, storage failure, browse recovery, safe share links, bilingual aliases, 3-language copy and HTML integration.");
